{% set name = "ibis-substrait" %}
{% set version = "2.28.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ibis_substrait-{{ version }}.tar.gz
  sha256: f495ed7dfcdc7f08d000dd5ddc5d730a329963a7ac2ad927a181156cc00e1c60

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python >=3.8
    - pip
    - poetry-core
  host:
    - pip
    - python >=3.8
    - poetry-core
  run:
    - ibis-framework-core >=3
    - protobuf ==3.20.1
    - python >=3.8
    - sqlalchemy >=1.4,<2

test:
  imports:
    - ibis_substrait

about:
  home: https://github.com/ibis-project/ibis-substrait
  summary: Subtrait compiler for ibis
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
    - cpcloud
