{% set name = "ibis-substrait" %}
{% set version = "2.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ibis-substrait-{{ version }}.tar.gz
  sha256: d6bf9cc8fe2ac1de28fc21a7955b0dd7942a22996d1f0479dd7e38378e6ab9ba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python >=3.6,<3.11
    - pip
    - poetry-core
  host:
    - pip
    - python >=3.6,<3.11
    - poetry-core
  run:
    - ibis-framework-core >=2,<4
    - packaging >=21.3,<22.0
    - platformdirs <2.5.3
    - protobuf >=3.20,<3.21
    - python >=3.6,<3.11

test:
  imports:
    - ibis_substrait
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ibis-project/ibis-substrait
  summary: Subtrait compiler for ibis
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
    - cpcloud
