{% set name = "ibis-substrait" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ibis_substrait-{{ version }}.tar.gz
  sha256: eb85960dceda6bcd6ed44e177e7b899a5f4214f16b3337f3cf9a4f01114c9841

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python >=3.9
    - pip
    - poetry-core
  host:
    - pip
    - python >=3.9
    - poetry-core
  run:
    - ibis-framework-core >=4
    - python >=3.9
    - python-substrait >=0.2.1
    - pyyaml >=5
    - sqlalchemy >=1.4,<2

test:
  imports:
    - ibis_substrait

about:
  home: https://github.com/ibis-project/ibis-substrait
  summary: Subtrait compiler for ibis
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
    - cpcloud
