{% set name = "ibis-substrait" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ibis_substrait-{{ version }}.tar.gz
  sha256: 600eac3d69699cb2eca5d6ecaa6f1072d0cfee8158d51d78b3b3d0c6f92ec089

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python >=3.9
    - pip
    - poetry-core
  host:
    - pip
    - python >=3.9
    - poetry-core
  run:
    - ibis-framework-core >=9
    - packaging >=21.3
    - python >=3.9
    - python-substrait >=0.2.1
    - pyyaml >=5

test:
  imports:
    - ibis_substrait

about:
  home: https://github.com/ibis-project/ibis-substrait
  summary: Subtrait compiler for ibis
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
    - cpcloud
