{% set name = "ibis-substrait" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ibis-substrait-{{ version }}.tar.gz
  sha256: dbd09c9c1ca84de62c408a2226103ee4676ce5ad343d9f90359b7bab35e606b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python >=3.6,<3.11
    - pip
    - poetry-core
  host:
    - pip
    - python >=3.6,<3.11
    - poetry-core
  run:
    - ibis-framework-core >=2,<4
    - packaging >=21.3,<22.0
    - platformdirs <2.5.3
    - protobuf >=3.19,<3.20
    - python >=3.6,<3.11

test:
  imports:
    - ibis_substrait
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ibis-project/ibis-substrait
  summary: Subtrait compiler for ibis
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
    - cpcloud
